repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 2.1.5
      hooks:
        - id: shellcheck
    - repo: local
      hooks:
        - id: builds-up-to-date
          name: Ensure build yamls are up-to-date
          entry: make build-yamls
          language: system
          types_or: [python, yaml]
        - id: test
          name: Run tests
          entry: make test
          language: system
          types: [shell]
