name: CI of the scripts themselves

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - name: pre-commit hooks
        run: env SKIP=test make pre-commit
      - name: tests
        run: make test
