name: status

on:
  push:

jobs:
  status:
    name: Testy mctest
    runs-on: [ 'self-hosted', 'ce', 'ubuntu' ]

    steps:
      - uses: actions/checkout@v2
      - name: pre
        id: pre
        run: ./pre-run.sh
      - name: printy
        run: echo "My run id is '${GITHUB_RUN_ID}'"
      - name: post
        if: ${{ always() }}
        run: ./post-run.sh test-gcc SUCCESS s3://something/tar.xz ${{ steps.pre.outputs.start }}
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
